# Site settings
title: Brian Luk 
email: 100freestyle46@gmail.com
url: https://thebrianluk.com
intro-quote: "We know what we are, but know not what we may be. - William Shakespeare"
end-quote: "Stay hungry, Stay foolish. - Steve Jobs"
font-family: Open Sans, -apple-system, BlinkMacSystemFont, Roboto, Arial, sans-serif

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  primary-white: '#ffffff'
  links: '#219ab3'
  text-highlight: 'rgba(10, 22, 197, 0.2)'
# Footer settings
footer: Brian Luk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hongszer
  - title: github
    url: https://github.com/bluk16
  - title: instagram
    url: https://instagram.com/hongszer
  - title: linkedin
    url: https://www.linkedin.com/in/bluk/

# Build settings
markdown: kramdown
permalink: pretty
